[2021-07-08T14:05:21.312485+00:00] php.INFO: User Deprecated: Since symfony/security-bundle 5.3: The "security.command.user_password_encoder" service is deprecated, use "security.command.user_password_hash" instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since symfony/security-bundle 5.3: The \"security.command.user_password_encoder\" service is deprecated, use \"security.command.user_password_hash\" instead. at /Users/andy/Documents/Project/symfony4_web/var/cache/dev/ContainerHsAVAYw/getSecurity_Command_UserPasswordEncoderService.php:22)"} []
[2021-07-08T14:05:21.314331+00:00] php.INFO: User Deprecated: Since symfony/security-bundle 5.3: The "security.encoder_factory.generic" service is deprecated, use "security.password_hasher_factory" instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since symfony/security-bundle 5.3: The \"security.encoder_factory.generic\" service is deprecated, use \"security.password_hasher_factory\" instead. at /Users/andy/Documents/Project/symfony4_web/var/cache/dev/ContainerHsAVAYw/getSecurity_EncoderFactory_GenericService.php:22)"} []
[2021-07-08T14:05:21.315731+00:00] php.INFO: User Deprecated: Since symfony/security-core 5.3: The "Symfony\Component\Security\Core\Encoder\EncoderFactory" class is deprecated, use "Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactory" instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since symfony/security-core 5.3: The \"Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactory\" class is deprecated, use \"Symfony\\Component\\PasswordHasher\\Hasher\\PasswordHasherFactory\" instead. at /Users/andy/Documents/Project/symfony4_web/vendor/symfony/security-core/Encoder/EncoderFactory.php:20)"} []
[2021-07-08T14:05:21.316369+00:00] php.INFO: User Deprecated: Since symfony/security-core 5.3: The "Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface" class is deprecated, use "Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactoryInterface" instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since symfony/security-core 5.3: The \"Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactoryInterface\" class is deprecated, use \"Symfony\\Component\\PasswordHasher\\Hasher\\PasswordHasherFactoryInterface\" instead. at /Users/andy/Documents/Project/symfony4_web/vendor/symfony/security-core/Encoder/EncoderFactoryInterface.php:17)"} []
[2021-07-08T14:05:21.515733+00:00] php.INFO: User Deprecated: Since symfony/security-bundle 5.3: The "security.command.user_password_encoder" service is deprecated, use "security.command.user_password_hash" instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since symfony/security-bundle 5.3: The \"security.command.user_password_encoder\" service is deprecated, use \"security.command.user_password_hash\" instead. at /Users/andy/Documents/Project/symfony4_web/var/cache/dev/ContainerHsAVAYw/getSecurity_Command_UserPasswordEncoderService.php:22)"} []
[2021-07-08T14:05:21.520871+00:00] php.INFO: User Deprecated: Since symfony/security-bundle 5.3: The "security.encoder_factory.generic" service is deprecated, use "security.password_hasher_factory" instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since symfony/security-bundle 5.3: The \"security.encoder_factory.generic\" service is deprecated, use \"security.password_hasher_factory\" instead. at /Users/andy/Documents/Project/symfony4_web/var/cache/dev/ContainerHsAVAYw/getSecurity_EncoderFactory_GenericService.php:22)"} []
[2021-07-08T14:05:21.521463+00:00] php.INFO: User Deprecated: Since symfony/security-core 5.3: The "Symfony\Component\Security\Core\Encoder\EncoderFactory" class is deprecated, use "Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactory" instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since symfony/security-core 5.3: The \"Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactory\" class is deprecated, use \"Symfony\\Component\\PasswordHasher\\Hasher\\PasswordHasherFactory\" instead. at /Users/andy/Documents/Project/symfony4_web/vendor/symfony/security-core/Encoder/EncoderFactory.php:20)"} []
[2021-07-08T14:05:21.521813+00:00] php.INFO: User Deprecated: Since symfony/security-core 5.3: The "Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface" class is deprecated, use "Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactoryInterface" instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since symfony/security-core 5.3: The \"Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactoryInterface\" class is deprecated, use \"Symfony\\Component\\PasswordHasher\\Hasher\\PasswordHasherFactoryInterface\" instead. at /Users/andy/Documents/Project/symfony4_web/vendor/symfony/security-core/Encoder/EncoderFactoryInterface.php:17)"} []
[2021-07-08T14:52:54.706460+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/config/routes/dev/web_profiler.yaml {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/var/www/symfony4_web/vendor/symfony/config/Resource/FileResource.php","line":65,"trace":[{"file":"/var/www/symfony4_web/vendor/symfony/config/Resource/SelfCheckingResourceChecker.php","line":34,"function":"isFresh","class":"Symfony\\Component\\Config\\Resource\\FileResource","type":"->"}],"count":1}}} []
[2021-07-08T14:52:59.055036+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://symfony.test/"" at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/\" at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-07-08T14:53:00.632841+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://symfony.test/favicon.ico" (from "http://symfony.test/")" at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-08T14:53:01.079886+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/config/routes/dev/web_profiler.yaml {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/var/www/symfony4_web/vendor/symfony/config/Resource/FileResource.php","line":65,"trace":[{"file":"/var/www/symfony4_web/vendor/symfony/config/Resource/SelfCheckingResourceChecker.php","line":34,"function":"isFresh","class":"Symfony\\Component\\Config\\Resource\\FileResource","type":"->"}],"count":1}}} []
[2021-07-08T14:53:01.987206+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occurred in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused 	Is the server running on host "127.0.0.1" and accepting 	TCP/IP connections on port 5432? at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 88) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432? at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:88)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432? at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432? at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-07-08T14:53:02.003747+00:00] php.CRITICAL: Uncaught Exception: An exception occurred in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused 	Is the server running on host "127.0.0.1" and accepting 	TCP/IP connections on port 5432? {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432? at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:88)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432? at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432? at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-08T14:53:02.029509+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused 	Is the server running on host "127.0.0.1" and accepting 	TCP/IP connections on port 5432?" at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 88 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432? at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:88)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432? at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432? at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-08T14:53:03.672053+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occurred in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused 	Is the server running on host "127.0.0.1" and accepting 	TCP/IP connections on port 5432? at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 88) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432? at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:88)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432? at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432? at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-07-08T14:53:03.676486+00:00] php.CRITICAL: Uncaught Exception: An exception occurred in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused 	Is the server running on host "127.0.0.1" and accepting 	TCP/IP connections on port 5432? {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432? at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:88)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432? at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432? at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432? at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:88)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432? at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432? at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-08T15:11:14.899234+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://symfony.test/"" at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/\" at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-07-08T15:11:15.432531+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://symfony.test/favicon.ico" (from "http://symfony.test/")" at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-08T15:11:15.736106+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-07-08T15:11:15.746143+00:00] php.CRITICAL: Uncaught Exception: An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-08T15:11:15.758827+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-08T15:11:16.834928+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-07-08T15:11:16.839008+00:00] php.CRITICAL: Uncaught Exception: An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-08T15:40:49.240499+00:00] php.DEBUG: Warning: filemtime(): stat failed for /var/www/symfony4_web/config/routes/dev/web_profiler.yaml {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/Users/andy/Documents/Project/symfony4_web/vendor/symfony/config/Resource/FileResource.php","line":65,"trace":[{"file":"/Users/andy/Documents/Project/symfony4_web/vendor/symfony/config/Resource/SelfCheckingResourceChecker.php","line":34,"function":"isFresh","class":"Symfony\\Component\\Config\\Resource\\FileResource","type":"->"}],"count":1}}} []
[2021-07-08T15:42:33.602014+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.en.xlf {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/var/www/symfony4_web/vendor/symfony/config/Resource/FileResource.php","line":65,"trace":[{"file":"/var/www/symfony4_web/vendor/symfony/config/Resource/SelfCheckingResourceChecker.php","line":34,"function":"isFresh","class":"Symfony\\Component\\Config\\Resource\\FileResource","type":"->"}],"count":1}}} []
[2021-07-08T15:42:33.745690+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.af.xlf [] []
[2021-07-08T15:42:33.839054+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.ar.xlf [] []
[2021-07-08T15:42:33.924146+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.az.xlf [] []
[2021-07-08T15:42:34.008608+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.be.xlf [] []
[2021-07-08T15:42:34.096706+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.bg.xlf [] []
[2021-07-08T15:42:34.189063+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.bs.xlf [] []
[2021-07-08T15:42:34.274070+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.ca.xlf [] []
[2021-07-08T15:42:34.362291+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.cs.xlf [] []
[2021-07-08T15:42:34.453537+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.cy.xlf [] []
[2021-07-08T15:42:34.517679+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.da.xlf [] []
[2021-07-08T15:42:34.608544+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.de.xlf [] []
[2021-07-08T15:42:34.696034+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.el.xlf [] []
[2021-07-08T15:42:34.787356+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.es.xlf [] []
[2021-07-08T15:42:34.873400+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.et.xlf [] []
[2021-07-08T15:42:34.950749+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.eu.xlf [] []
[2021-07-08T15:42:35.038908+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.fa.xlf [] []
[2021-07-08T15:42:35.127879+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.fi.xlf [] []
[2021-07-08T15:42:35.221233+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.fr.xlf [] []
[2021-07-08T15:42:35.312684+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.gl.xlf [] []
[2021-07-08T15:42:35.401043+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.he.xlf [] []
[2021-07-08T15:42:35.493037+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.hr.xlf [] []
[2021-07-08T15:42:35.580735+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.hu.xlf [] []
[2021-07-08T15:42:35.674809+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.hy.xlf [] []
[2021-07-08T15:42:35.763372+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.id.xlf [] []
[2021-07-08T15:42:35.850263+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.it.xlf [] []
[2021-07-08T15:42:35.940311+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.ja.xlf [] []
[2021-07-08T15:42:36.029799+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.lb.xlf [] []
[2021-07-08T15:42:36.119971+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.lt.xlf [] []
[2021-07-08T15:42:36.210252+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.lv.xlf [] []
[2021-07-08T15:42:36.295816+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.mn.xlf [] []
[2021-07-08T15:42:36.382888+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.nb.xlf [] []
[2021-07-08T15:42:36.545127+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.nl.xlf [] []
[2021-07-08T15:42:36.634701+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.nn.xlf [] []
[2021-07-08T15:42:36.726619+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.no.xlf [] []
[2021-07-08T15:42:36.817244+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.pl.xlf [] []
[2021-07-08T15:42:36.907400+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.pt.xlf [] []
[2021-07-08T15:42:36.994273+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.pt_BR.xlf [] []
[2021-07-08T15:42:37.090314+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.ro.xlf [] []
[2021-07-08T15:42:37.179912+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.ru.xlf [] []
[2021-07-08T15:42:37.275418+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.sk.xlf [] []
[2021-07-08T15:42:37.369881+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.sl.xlf [] []
[2021-07-08T15:42:37.463925+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.sq.xlf [] []
[2021-07-08T15:42:37.555277+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.sr_Cyrl.xlf [] []
[2021-07-08T15:42:37.663275+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.sr_Latn.xlf [] []
[2021-07-08T15:42:37.758130+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.sv.xlf [] []
[2021-07-08T15:42:37.854997+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.th.xlf [] []
[2021-07-08T15:42:37.947746+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.tl.xlf [] []
[2021-07-08T15:42:38.042842+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.tr.xlf [] []
[2021-07-08T15:42:38.131510+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.uk.xlf [] []
[2021-07-08T15:42:38.222823+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.uz.xlf [] []
[2021-07-08T15:42:38.319643+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.vi.xlf [] []
[2021-07-08T15:42:38.410882+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.zh_CN.xlf [] []
[2021-07-08T15:42:38.523390+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/vendor/symfony/validator/Resources/translations/validators.zh_TW.xlf [] []
[2021-07-08T15:42:38.617559+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/config/routes/dev/web_profiler.yaml [] []
[2021-07-08T15:42:39.835404+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/andy/Documents/Project/symfony4_web/config/routes/dev/web_profiler.yaml [] []
[2021-07-08T15:44:45.300228+00:00] console.CRITICAL: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2021-07-08T15:44:45.314598+00:00] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2021-07-08T15:45:56.543057+00:00] console.CRITICAL: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2021-07-08T15:45:56.557562+00:00] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2021-07-08T15:46:06.067025+00:00] console.CRITICAL: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2021-07-08T15:46:06.080116+00:00] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2021-07-08T15:47:42.907968+00:00] console.CRITICAL: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony4_web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2021-07-08T15:47:42.921870+00:00] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2021-07-08T15:48:13.605350+00:00] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2021-07-08T17:48:52.650440+00:00] console.CRITICAL: Error thrown while running command "'make:works'". Message: "Command "make:works" is not defined.  Did you mean one of these?     make:auth     make:command     make:controller     make:crud     make:docker:database     make:entity     make:fixtures     make:form     make:functional-test     make:message     make:messenger-middleware     make:migration     make:registration-form     make:reset-password     make:serializer:encoder     make:serializer:normalizer     make:subscriber     make:test     make:twig-extension     make:unit-test     make:user     make:validator     make:voter" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"make:works\" is not defined.\n\nDid you mean one of these?\n    make:auth\n    make:command\n    make:controller\n    make:crud\n    make:docker:database\n    make:entity\n    make:fixtures\n    make:form\n    make:functional-test\n    make:message\n    make:messenger-middleware\n    make:migration\n    make:registration-form\n    make:reset-password\n    make:serializer:encoder\n    make:serializer:normalizer\n    make:subscriber\n    make:test\n    make:twig-extension\n    make:unit-test\n    make:user\n    make:validator\n    make:voter at /var/www/symfony4_web/vendor/symfony/console/Application.php:682)","command":"'make:works'","message":"Command \"make:works\" is not defined.\n\nDid you mean one of these?\n    make:auth\n    make:command\n    make:controller\n    make:crud\n    make:docker:database\n    make:entity\n    make:fixtures\n    make:form\n    make:functional-test\n    make:message\n    make:messenger-middleware\n    make:migration\n    make:registration-form\n    make:reset-password\n    make:serializer:encoder\n    make:serializer:normalizer\n    make:subscriber\n    make:test\n    make:twig-extension\n    make:unit-test\n    make:user\n    make:validator\n    make:voter"} []
[2021-07-08T17:49:40.755793+00:00] console.DEBUG: Command "make:entity" exited with code "1" {"command":"make:entity","code":1} []
[2021-07-08T17:57:34.096494+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-08T17:57:34.208675+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-08T17:57:34.236265+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-08T17:58:42.044464+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-08T17:58:42.216479+00:00] doctrine.DEBUG: CREATE TABLE doctrine_migration_versions (version VARCHAR(191) NOT NULL, executed_at DATETIME DEFAULT NULL, execution_time INT DEFAULT NULL, PRIMARY KEY(version)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB [] []
[2021-07-08T17:58:42.411738+00:00] doctrine.DEBUG: SELECT * FROM doctrine_migration_versions [] []
[2021-07-08T17:58:42.430090+00:00] doctrine.DEBUG: SELECT * FROM doctrine_migration_versions [] []
[2021-07-08T17:58:42.433914+00:00] doctrine.DEBUG: SELECT * FROM doctrine_migration_versions [] []
[2021-07-08T17:58:42.542107+00:00] doctrine.DEBUG: "START TRANSACTION" [] []
[2021-07-08T17:58:42.737320+00:00] doctrine.DEBUG: CREATE TABLE works (id INT AUTO_INCREMENT NOT NULL, job VARCHAR(200) NOT NULL, level INT NOT NULL, estimated_duration INT NOT NULL, dev_id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB [] []
[2021-07-08T17:58:42.791625+00:00] doctrine.DEBUG: INSERT INTO doctrine_migration_versions (version, executed_at, execution_time) VALUES (?, ?, ?) ["DoctrineMigrations\\Version [...]","2021-07-08T17:58:42+00:00",239] []
[2021-07-08T17:58:42.807714+00:00] doctrine.DEBUG: "COMMIT" [] []
[2021-07-09T15:29:45.445692+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://symfony.test/"" at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/\" at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-07-09T15:29:45.614688+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:45.652364+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:45.835427+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony_enuygun' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-07-09T15:29:45.863887+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'symfony_enuygun' /*!50116 AND c.constraint_schema = 'symfony_enuygun' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-07-09T15:29:45.871607+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'symfony_enuygun' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-07-09T15:29:45.878437+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-07-09T15:29:46.326399+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://symfony.test/favicon.ico" (from "http://symfony.test/")" at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-09T15:29:46.709051+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:46.716382+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:46.756328+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony_enuygun' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-07-09T15:29:46.767349+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'symfony_enuygun' /*!50116 AND c.constraint_schema = 'symfony_enuygun' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-07-09T15:29:46.770537+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'symfony_enuygun' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-07-09T15:29:46.773600+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-07-09T15:29:46.790583+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\Migrations\Exception\MetadataStorageError: The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php line 13) {"exception":"[object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)"} []
[2021-07-09T15:29:46.798114+00:00] php.CRITICAL: Uncaught Exception: The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. {"exception":"[object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-09T15:29:46.804318+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\Migrations\Exception\MetadataStorageError: "The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue." at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php line 13 {"exception":"[object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-09T15:29:47.198679+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:47.203413+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:47.208232+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony_enuygun' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-07-09T15:29:47.213981+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'symfony_enuygun' /*!50116 AND c.constraint_schema = 'symfony_enuygun' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-07-09T15:29:47.216892+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'symfony_enuygun' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-07-09T15:29:47.219682+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-07-09T15:29:47.232608+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\Migrations\Exception\MetadataStorageError: The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php line 13) {"exception":"[object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)"} []
[2021-07-09T15:29:47.235715+00:00] php.CRITICAL: Uncaught Exception: The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. {"exception":"[object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)\n[previous exception] [object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-09T15:29:47.444437+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://symfony.test/"" at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/\" at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-07-09T15:29:47.490490+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:47.496956+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:47.510784+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony_enuygun' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-07-09T15:29:47.525472+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'symfony_enuygun' /*!50116 AND c.constraint_schema = 'symfony_enuygun' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-07-09T15:29:47.529298+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'symfony_enuygun' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-07-09T15:29:47.533542+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-07-09T15:29:47.845045+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://symfony.test/favicon.ico" (from "http://symfony.test/")" at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-09T15:29:48.154176+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:48.159079+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:48.171820+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony_enuygun' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-07-09T15:29:48.180886+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'symfony_enuygun' /*!50116 AND c.constraint_schema = 'symfony_enuygun' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-07-09T15:29:48.183688+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'symfony_enuygun' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-07-09T15:29:48.186772+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-07-09T15:29:48.201192+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\Migrations\Exception\MetadataStorageError: The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php line 13) {"exception":"[object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)"} []
[2021-07-09T15:29:48.208894+00:00] php.CRITICAL: Uncaught Exception: The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. {"exception":"[object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-09T15:29:48.218241+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\Migrations\Exception\MetadataStorageError: "The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue." at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php line 13 {"exception":"[object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-09T15:29:48.512682+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://symfony.test/"" at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/\" at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-07-09T15:29:48.557387+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:48.561302+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:48.572694+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony_enuygun' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-07-09T15:29:48.581412+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'symfony_enuygun' /*!50116 AND c.constraint_schema = 'symfony_enuygun' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-07-09T15:29:48.584853+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'symfony_enuygun' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-07-09T15:29:48.587690+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-07-09T15:29:48.657189+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:48.661955+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:48.668715+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony_enuygun' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-07-09T15:29:48.673796+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'symfony_enuygun' /*!50116 AND c.constraint_schema = 'symfony_enuygun' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-07-09T15:29:48.677981+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'symfony_enuygun' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-07-09T15:29:48.683135+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-07-09T15:29:48.708797+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\Migrations\Exception\MetadataStorageError: The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php line 13) {"exception":"[object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)"} []
[2021-07-09T15:29:48.712480+00:00] php.CRITICAL: Uncaught Exception: The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. {"exception":"[object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)\n[previous exception] [object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-09T15:29:48.837005+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://symfony.test/favicon.ico" (from "http://symfony.test/")" at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-09T15:29:49.094050+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:49.097965+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:49.109248+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony_enuygun' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-07-09T15:29:49.116998+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'symfony_enuygun' /*!50116 AND c.constraint_schema = 'symfony_enuygun' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-07-09T15:29:49.120045+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'symfony_enuygun' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-07-09T15:29:49.122842+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-07-09T15:29:49.137033+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\Migrations\Exception\MetadataStorageError: The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php line 13) {"exception":"[object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)"} []
[2021-07-09T15:29:49.143860+00:00] php.CRITICAL: Uncaught Exception: The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. {"exception":"[object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-09T15:29:49.149761+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\Migrations\Exception\MetadataStorageError: "The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue." at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php line 13 {"exception":"[object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-09T15:29:49.527599+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:49.532075+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:49.537260+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony_enuygun' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-07-09T15:29:49.541995+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'symfony_enuygun' /*!50116 AND c.constraint_schema = 'symfony_enuygun' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-07-09T15:29:49.544780+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'symfony_enuygun' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-07-09T15:29:49.547928+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-07-09T15:29:49.561895+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\Migrations\Exception\MetadataStorageError: The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php line 13) {"exception":"[object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)"} []
[2021-07-09T15:29:49.565344+00:00] php.CRITICAL: Uncaught Exception: The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. {"exception":"[object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)\n[previous exception] [object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-09T15:29:49.781978+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://symfony.test/"" at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/\" at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-07-09T15:29:49.826360+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:49.830358+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:49.844645+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony_enuygun' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-07-09T15:29:49.854675+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'symfony_enuygun' /*!50116 AND c.constraint_schema = 'symfony_enuygun' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-07-09T15:29:49.860294+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'symfony_enuygun' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-07-09T15:29:49.864276+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-07-09T15:29:50.130522+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://symfony.test/favicon.ico" (from "http://symfony.test/")" at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-09T15:29:50.386680+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:50.391491+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:50.403023+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony_enuygun' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-07-09T15:29:50.411869+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'symfony_enuygun' /*!50116 AND c.constraint_schema = 'symfony_enuygun' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-07-09T15:29:50.414980+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'symfony_enuygun' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-07-09T15:29:50.418442+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-07-09T15:29:50.433957+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\Migrations\Exception\MetadataStorageError: The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php line 13) {"exception":"[object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)"} []
[2021-07-09T15:29:50.446703+00:00] php.CRITICAL: Uncaught Exception: The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. {"exception":"[object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-09T15:29:50.456824+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\Migrations\Exception\MetadataStorageError: "The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue." at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php line 13 {"exception":"[object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-09T15:29:50.834929+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:50.839939+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-07-09T15:29:50.845487+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony_enuygun' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-07-09T15:29:50.851282+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'symfony_enuygun' /*!50116 AND c.constraint_schema = 'symfony_enuygun' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-07-09T15:29:50.854483+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'symfony_enuygun' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-07-09T15:29:50.857690+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-07-09T15:29:50.870618+00:00] request.CRITICAL: Exception thrown when handling an exception (Doctrine\Migrations\Exception\MetadataStorageError: The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php line 13) {"exception":"[object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)"} []
[2021-07-09T15:29:50.873821+00:00] php.CRITICAL: Uncaught Exception: The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. {"exception":"[object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)\n[previous exception] [object] (Doctrine\\Migrations\\Exception\\MetadataStorageError(code: 0): The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. at /var/www/symfony4_web/vendor/doctrine/migrations/lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13)\n[previous exception] [object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://symfony.test/favicon.ico\" (from \"http://symfony.test/\") at /var/www/symfony4_web/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony4_web/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-09T15:43:45.090378+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Class 'http\Client' not found" {"exception":"[object] (Error(code: 0): Class 'http\\Client' not found at /var/www/symfony4_web/src/Command/JobServiceCommand.php:23)","command":"app:job-get","message":"Class 'http\\Client' not found"} []
[2021-07-09T15:43:45.120195+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-09T15:43:45.135314+00:00] php.CRITICAL: Uncaught Error: Class 'http\Client' not found {"exception":"[object] (Error(code: 0): Class 'http\\Client' not found at /var/www/symfony4_web/src/Command/JobServiceCommand.php:23)"} []
[2021-07-09T16:12:40.619724+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Argument 1 passed to Symfony\Component\Console\Formatter\OutputFormatter::format() must be of the type string or null, object given, called in /var/www/symfony4_web/vendor/symfony/console/Output/Output.php on line 157" {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Symfony\\Component\\Console\\Formatter\\OutputFormatter::format() must be of the type string or null, object given, called in /var/www/symfony4_web/vendor/symfony/console/Output/Output.php on line 157 at /var/www/symfony4_web/vendor/symfony/console/Formatter/OutputFormatter.php:133)","command":"app:job-get","message":"Argument 1 passed to Symfony\\Component\\Console\\Formatter\\OutputFormatter::format() must be of the type string or null, object given, called in /var/www/symfony4_web/vendor/symfony/console/Output/Output.php on line 157"} []
[2021-07-09T16:12:40.633548+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-09T16:12:40.641042+00:00] php.CRITICAL: Uncaught Error: Argument 1 passed to Symfony\Component\Console\Formatter\OutputFormatter::format() must be of the type string or null, object given, called in /var/www/symfony4_web/vendor/symfony/console/Output/Output.php on line 157 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Symfony\\Component\\Console\\Formatter\\OutputFormatter::format() must be of the type string or null, object given, called in /var/www/symfony4_web/vendor/symfony/console/Output/Output.php on line 157 at /var/www/symfony4_web/vendor/symfony/console/Formatter/OutputFormatter.php:133)"} []
[2021-07-10T23:47:00.683581+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Notice: Array to string conversion" {"exception":"[object] (ErrorException(code: 0): Notice: Array to string conversion at /var/www/symfony4_web/src/Command/JobServiceCommand.php:43)","command":"app:job-get","message":"Notice: Array to string conversion"} []
[2021-07-10T23:47:00.704158+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-10T23:48:19.371321+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Object of class stdClass could not be converted to string" {"exception":"[object] (Error(code: 0): Object of class stdClass could not be converted to string at /var/www/symfony4_web/src/Command/JobServiceCommand.php:37)","command":"app:job-get","message":"Object of class stdClass could not be converted to string"} []
[2021-07-10T23:48:19.387435+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-10T23:48:19.395041+00:00] php.CRITICAL: Uncaught Error: Object of class stdClass could not be converted to string {"exception":"[object] (Error(code: 0): Object of class stdClass could not be converted to string at /var/www/symfony4_web/src/Command/JobServiceCommand.php:37)"} []
[2021-07-10T23:49:44.452604+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Warning: get_object_vars() expects parameter 1 to be object, int given" {"exception":"[object] (ErrorException(code: 0): Warning: get_object_vars() expects parameter 1 to be object, int given at /var/www/symfony4_web/src/Command/JobServiceCommand.php:37)","command":"app:job-get","message":"Warning: get_object_vars() expects parameter 1 to be object, int given"} []
[2021-07-10T23:49:44.466641+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-10T23:53:02.046955+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Cannot use [] for reading" {"exception":"[object] (Error(code: 0): Cannot use [] for reading at /var/www/symfony4_web/src/Command/JobServiceCommand.php:45)","command":"app:job-get","message":"Cannot use [] for reading"} []
[2021-07-10T23:53:02.064618+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-10T23:53:02.076614+00:00] php.CRITICAL: Uncaught Error: Cannot use [] for reading {"exception":"[object] (Error(code: 0): Cannot use [] for reading at /var/www/symfony4_web/src/Command/JobServiceCommand.php:45)"} []
[2021-07-11T00:24:54.328532+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Notice: Undefined index: zorluk" {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: zorluk at /var/www/symfony4_web/src/Library/WorkConsole.php:51)","command":"app:job-get","message":"Notice: Undefined index: zorluk"} []
[2021-07-11T00:24:54.341997+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:25:31.249637+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Notice: Undefined index: zorluk" {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: zorluk at /var/www/symfony4_web/src/Library/WorkConsole.php:52)","command":"app:job-get","message":"Notice: Undefined index: zorluk"} []
[2021-07-11T00:25:31.263400+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:27:33.027934+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Warning: get_object_vars() expects parameter 1 to be object, array given" {"exception":"[object] (ErrorException(code: 0): Warning: get_object_vars() expects parameter 1 to be object, array given at /var/www/symfony4_web/src/Command/JobServiceCommand.php:34)","command":"app:job-get","message":"Warning: get_object_vars() expects parameter 1 to be object, array given"} []
[2021-07-11T00:27:33.041469+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:28:29.581354+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Warning: get_object_vars() expects parameter 1 to be object, array given" {"exception":"[object] (ErrorException(code: 0): Warning: get_object_vars() expects parameter 1 to be object, array given at /var/www/symfony4_web/src/Command/JobServiceCommand.php:35)","command":"app:job-get","message":"Warning: get_object_vars() expects parameter 1 to be object, array given"} []
[2021-07-11T00:28:29.595749+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:29:13.037193+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Notice: Undefined variable: aa" {"exception":"[object] (ErrorException(code: 0): Notice: Undefined variable: aa at /var/www/symfony4_web/src/Command/JobServiceCommand.php:35)","command":"app:job-get","message":"Notice: Undefined variable: aa"} []
[2021-07-11T00:29:13.053771+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:29:35.286995+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Warning: get_object_vars() expects parameter 1 to be object, array given" {"exception":"[object] (ErrorException(code: 0): Warning: get_object_vars() expects parameter 1 to be object, array given at /var/www/symfony4_web/src/Command/JobServiceCommand.php:35)","command":"app:job-get","message":"Warning: get_object_vars() expects parameter 1 to be object, array given"} []
[2021-07-11T00:29:35.302797+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:30:46.125454+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Notice: Undefined index: zorluk" {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: zorluk at /var/www/symfony4_web/src/Library/WorkConsole.php:52)","command":"app:job-get","message":"Notice: Undefined index: zorluk"} []
[2021-07-11T00:30:46.141171+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:31:07.342197+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Warning: get_object_vars() expects parameter 1 to be object, array given" {"exception":"[object] (ErrorException(code: 0): Warning: get_object_vars() expects parameter 1 to be object, array given at /var/www/symfony4_web/src/Command/JobServiceCommand.php:35)","command":"app:job-get","message":"Warning: get_object_vars() expects parameter 1 to be object, array given"} []
[2021-07-11T00:31:07.357637+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:32:58.741439+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Notice: Undefined index: data" {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: data at /var/www/symfony4_web/src/Command/JobServiceCommand.php:34)","command":"app:job-get","message":"Notice: Undefined index: data"} []
[2021-07-11T00:32:58.755142+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:33:23.349931+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Cannot use [] for reading" {"exception":"[object] (Error(code: 0): Cannot use [] for reading at /var/www/symfony4_web/src/Command/JobServiceCommand.php:34)","command":"app:job-get","message":"Cannot use [] for reading"} []
[2021-07-11T00:33:23.362461+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:33:23.368991+00:00] php.CRITICAL: Uncaught Error: Cannot use [] for reading {"exception":"[object] (Error(code: 0): Cannot use [] for reading at /var/www/symfony4_web/src/Command/JobServiceCommand.php:34)"} []
[2021-07-11T00:33:33.646403+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Notice: Undefined index: id" {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: id at /var/www/symfony4_web/src/Command/JobServiceCommand.php:34)","command":"app:job-get","message":"Notice: Undefined index: id"} []
[2021-07-11T00:33:33.659708+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:33:44.911721+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Notice: Undefined index: level" {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: level at /var/www/symfony4_web/src/Command/JobServiceCommand.php:34)","command":"app:job-get","message":"Notice: Undefined index: level"} []
[2021-07-11T00:33:44.924032+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:33:54.054494+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Warning: get_object_vars() expects parameter 1 to be object, array given" {"exception":"[object] (ErrorException(code: 0): Warning: get_object_vars() expects parameter 1 to be object, array given at /var/www/symfony4_web/src/Command/JobServiceCommand.php:35)","command":"app:job-get","message":"Warning: get_object_vars() expects parameter 1 to be object, array given"} []
[2021-07-11T00:33:54.069282+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:34:08.955293+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Notice: Undefined index: key" {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: key at /var/www/symfony4_web/src/Command/JobServiceCommand.php:34)","command":"app:job-get","message":"Notice: Undefined index: key"} []
[2021-07-11T00:34:08.969219+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:37:56.996330+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Warning: get_object_vars() expects parameter 1 to be object, array given" {"exception":"[object] (ErrorException(code: 0): Warning: get_object_vars() expects parameter 1 to be object, array given at /var/www/symfony4_web/src/Command/JobServiceCommand.php:35)","command":"app:job-get","message":"Warning: get_object_vars() expects parameter 1 to be object, array given"} []
[2021-07-11T00:37:57.011513+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:38:24.305763+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Notice: Undefined index: value" {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: value at /var/www/symfony4_web/src/Command/JobServiceCommand.php:34)","command":"app:job-get","message":"Notice: Undefined index: value"} []
[2021-07-11T00:38:24.319371+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:38:33.409241+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Cannot use [] for reading" {"exception":"[object] (Error(code: 0): Cannot use [] for reading at /var/www/symfony4_web/src/Command/JobServiceCommand.php:34)","command":"app:job-get","message":"Cannot use [] for reading"} []
[2021-07-11T00:38:33.423379+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:38:33.429316+00:00] php.CRITICAL: Uncaught Error: Cannot use [] for reading {"exception":"[object] (Error(code: 0): Cannot use [] for reading at /var/www/symfony4_web/src/Command/JobServiceCommand.php:34)"} []
[2021-07-11T00:38:47.907629+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Warning: get_object_vars() expects parameter 1 to be object, array given" {"exception":"[object] (ErrorException(code: 0): Warning: get_object_vars() expects parameter 1 to be object, array given at /var/www/symfony4_web/src/Command/JobServiceCommand.php:35)","command":"app:job-get","message":"Warning: get_object_vars() expects parameter 1 to be object, array given"} []
[2021-07-11T00:38:47.921790+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:39:05.836891+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Warning: get_object_vars() expects parameter 1 to be object, int given" {"exception":"[object] (ErrorException(code: 0): Warning: get_object_vars() expects parameter 1 to be object, int given at /var/www/symfony4_web/src/Command/JobServiceCommand.php:35)","command":"app:job-get","message":"Warning: get_object_vars() expects parameter 1 to be object, int given"} []
[2021-07-11T00:39:05.850709+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:40:30.965027+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Warning: get_object_vars() expects parameter 1 to be object, array given" {"exception":"[object] (ErrorException(code: 0): Warning: get_object_vars() expects parameter 1 to be object, array given at /var/www/symfony4_web/src/Command/JobServiceCommand.php:34)","command":"app:job-get","message":"Warning: get_object_vars() expects parameter 1 to be object, array given"} []
[2021-07-11T00:40:30.977794+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:40:45.273720+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Notice: Undefined index: zorluk" {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: zorluk at /var/www/symfony4_web/src/Library/WorkConsole.php:52)","command":"app:job-get","message":"Notice: Undefined index: zorluk"} []
[2021-07-11T00:40:45.287579+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:42:06.635157+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Warning: json_decode() expects parameter 1 to be string, array given" {"exception":"[object] (ErrorException(code: 0): Warning: json_decode() expects parameter 1 to be string, array given at /var/www/symfony4_web/src/Library/WorkConsole.php:43)","command":"app:job-get","message":"Warning: json_decode() expects parameter 1 to be string, array given"} []
[2021-07-11T00:42:06.647384+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:42:26.621427+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Warning: json_decode() expects parameter 1 to be string, array given" {"exception":"[object] (ErrorException(code: 0): Warning: json_decode() expects parameter 1 to be string, array given at /var/www/symfony4_web/src/Library/WorkConsole.php:43)","command":"app:job-get","message":"Warning: json_decode() expects parameter 1 to be string, array given"} []
[2021-07-11T00:42:26.635091+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:43:23.892501+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Notice: Undefined index: zorluk" {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: zorluk at /var/www/symfony4_web/src/Library/WorkConsole.php:51)","command":"app:job-get","message":"Notice: Undefined index: zorluk"} []
[2021-07-11T00:43:23.904784+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T00:44:01.895799+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Warning: get_object_vars() expects parameter 1 to be object, array given" {"exception":"[object] (ErrorException(code: 0): Warning: get_object_vars() expects parameter 1 to be object, array given at /var/www/symfony4_web/src/Command/JobServiceCommand.php:52)","command":"app:job-get","message":"Warning: get_object_vars() expects parameter 1 to be object, array given"} []
[2021-07-11T00:44:01.909948+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T01:01:38.758990+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Call to undefined method App\Library\WorkConsole::getDoctrine()" {"exception":"[object] (Error(code: 0): Call to undefined method App\\Library\\WorkConsole::getDoctrine() at /var/www/symfony4_web/src/Library/WorkConsole.php:60)","command":"app:job-get","message":"Call to undefined method App\\Library\\WorkConsole::getDoctrine()"} []
[2021-07-11T01:01:38.787907+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T01:01:38.797971+00:00] php.CRITICAL: Uncaught Error: Call to undefined method App\Library\WorkConsole::getDoctrine() {"exception":"[object] (Error(code: 0): Call to undefined method App\\Library\\WorkConsole::getDoctrine() at /var/www/symfony4_web/src/Library/WorkConsole.php:60)"} []
[2021-07-11T01:01:54.056431+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Call to undefined method App\Library\WorkConsole::getDoctrine()" {"exception":"[object] (Error(code: 0): Call to undefined method App\\Library\\WorkConsole::getDoctrine() at /var/www/symfony4_web/src/Library/WorkConsole.php:60)","command":"app:job-get","message":"Call to undefined method App\\Library\\WorkConsole::getDoctrine()"} []
[2021-07-11T01:01:54.069489+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T01:01:54.076860+00:00] php.CRITICAL: Uncaught Error: Call to undefined method App\Library\WorkConsole::getDoctrine() {"exception":"[object] (Error(code: 0): Call to undefined method App\\Library\\WorkConsole::getDoctrine() at /var/www/symfony4_web/src/Library/WorkConsole.php:60)"} []
[2021-07-11T14:39:31.383806+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Call to a member function has() on null" {"exception":"[object] (Error(code: 0): Call to a member function has() on null at /var/www/symfony4_web/vendor/symfony/framework-bundle/Controller/AbstractController.php:377)","command":"app:job-get","message":"Call to a member function has() on null"} []
[2021-07-11T14:39:31.391623+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T14:39:31.399888+00:00] php.CRITICAL: Uncaught Error: Call to a member function has() on null {"exception":"[object] (Error(code: 0): Call to a member function has() on null at /var/www/symfony4_web/vendor/symfony/framework-bundle/Controller/AbstractController.php:377)"} []
[2021-07-11T14:40:23.179377+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Call to a member function has() on null" {"exception":"[object] (Error(code: 0): Call to a member function has() on null at /var/www/symfony4_web/vendor/symfony/framework-bundle/Controller/AbstractController.php:377)","command":"app:job-get","message":"Call to a member function has() on null"} []
[2021-07-11T14:40:23.193760+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T14:40:23.201298+00:00] php.CRITICAL: Uncaught Error: Call to a member function has() on null {"exception":"[object] (Error(code: 0): Call to a member function has() on null at /var/www/symfony4_web/vendor/symfony/framework-bundle/Controller/AbstractController.php:377)"} []
[2021-07-11T14:50:00.220550+00:00] console.CRITICAL: Error thrown while running command "app:job-get". Message: "Call to a member function has() on null" {"exception":"[object] (Error(code: 0): Call to a member function has() on null at /var/www/symfony4_web/vendor/symfony/framework-bundle/Controller/AbstractController.php:377)","command":"app:job-get","message":"Call to a member function has() on null"} []
[2021-07-11T14:50:00.229130+00:00] console.DEBUG: Command "app:job-get" exited with code "1" {"command":"app:job-get","code":1} []
[2021-07-11T14:50:00.237721+00:00] php.CRITICAL: Uncaught Error: Call to a member function has() on null {"exception":"[object] (Error(code: 0): Call to a member function has() on null at /var/www/symfony4_web/vendor/symfony/framework-bundle/Controller/AbstractController.php:377)"} []
